// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwIoTmivzEvwVNMvfkJL5DMnv_IOc_u8',
    appId: '1:910463717511:web:78ce49b8a72d6f2c146822',
    messagingSenderId: '910463717511',
    projectId: 'fairplay-lab',
    authDomain: 'fairplay-lab.firebaseapp.com',
    storageBucket: 'fairplay-lab.firebasestorage.app',
    measurementId: 'G-TW1RXBP5RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYtD5TFJOKIyK8bzAScKJOCqXdYw3HKFk',
    appId: '1:910463717511:android:ee3fc692edc6f20e146822',
    messagingSenderId: '910463717511',
    projectId: 'fairplay-lab',
    storageBucket: 'fairplay-lab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_2U6sJcexDjSrzBWReORL5WNP5a5LfY',
    appId: '1:910463717511:ios:d3fc58dab20a6bf8146822',
    messagingSenderId: '910463717511',
    projectId: 'fairplay-lab',
    storageBucket: 'fairplay-lab.firebasestorage.app',
    iosBundleId: 'com.fairplaylab.app',
  );
}
